version: '3.5'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ponto_db
    ports:
      - "3306:3306"
    networks:
      - hackaton_app_network
    expose:
      - 3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_HOST: 'mysql:3306/ponto_db'
      DB_USER: 'root'
      DB_PASS: '123456'
    ports:
      - "8080:8080"
    networks:
      - hackaton_app_network
    depends_on:
      mysql:
        condition: service_healthy
      mock:
        condition: service_started

networks:
  hackaton_app_network:
    name: "hackaton_app_network"
    driver: bridge